name: Test Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry into Environment
        uses: abatilo/actions-poetry@v2.1.0
      - name: Install Package
        run: poetry install
      - name: Test Package
        run: poetry run pytest
        env:
          tap_clockify_api_key: ${{ secrets.tap_clockify_api_key }}
          tap_clockify_workspace: ${{ secrets.tap_clockify_workspace }}

